name: Build EDDP EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Run command
      run: pyinstaller --onefile --noconsole -i ./eddplogo.ico -n eddp src/main.py